#!/usr/bin/env python

import unittest
from src.annotator import Annotator

class TestAnnotator(unittest.TestCase):

    def setUp(self):
        self.anno = Annotator()
        raw_entry1 = "comp10010_c0	   comp10010_c0_seq1:3-1250(-)	BDOR_007864-RA	 sp|Q7Z4T9|AAT1_HUMAN`Q7Z4T9`Q:533-644,H:400-513`37.39%ID`E:9e-08`RecName: Full=Protein MAATS1; AltName: Full=AMY-1-associating protein expressed in testis 1; Short=AAT-1; AltName: Full=MYCBP/AMY-1-associated testis-expressed protein 1;`Eukaryota; Metazoa; Chordata; Craniata; Vertebrata; Euteleostomi; Mammalia; Eutheria; Euarchontoglires; Primates; Haplorrhini; Catarrhini; Hominidae; Homo. .	  .	  .	  NOG84773^ Amy-1-Associating protein expressed in testis 1 (AAT-1)	  GO:0005739^cellular_component^mitochondrion	MAQPSHHKLAKRVFKSVYDAECSTADEKSDLKMFKNARNKATTAKMYARHEFSKEAGLEHYAYRKELTVTPSDYDRNSLTSGSTDSLSHSYNRISTRLRGGVNNPAERRVTNIVTAPSECKSKALGLDHFTPDTKVNVLEMKLNLSTEAENSPAQKYAYCKYFEEIKEKKVKTRGTQSLYRESSAQTLPYLPEVSNNERDLEQIELFKLPTILPGDGPPGLYQVEVLERARKRWAFARALKENLRRQIEEVKQQAKLSGNSVVLQAFEWEHWIEREEYIQECQMLRLEILIGMFNKREEKMHATSKVRIERSYEEILARRDASLHKNQVEYERGIRQLEIKRRRVPKCWRKENIVSQLGSPSSEFYGPQLRYGVNPARRHFVGGRKEFEARMDDLEKRAVKFTKLVCPFAKLKEWAKPKQRLLEIEQNFCSDENLQKMYETLTSLRKKAVKQKIVPKCLIQKTKPVLINKVISRSEYSMETKVEEDVEVHDISEKKASEGELKRIEDRKFRQSVEDKKQRAQYLLQELYNEEVEGMVQEYEGCTIGWIMRFLSEEMGRLQEQRLLHYITMLAQKERWRREAAEAGLRQKENNMRKIYEEVYKETMDVCLIGRKYLNTILDTDIPNIAHHKAEDEVLEMARIIDIDIQRWLDSLHDIQNPLNYNSLRYKLKKIMFPDLNEILKQMEIKQMLHNIIEEVLFDKVFTALEPYDICTFLVRELVDRLIDLDLYYFTSEETSNCSCTACECGENEREIRALLRKLIRRAVPGRRWKTPLERTVKELLVDLIKDVVEVTNTRGSIFESDSWTRFCKLQFSPSHMDLRHPSTHALKAPSSTTSSSTSINFLTGVHVHAEQERFWSESEFSSLVKNREDISTVFEYMPEAFYYDPSETADSDTDTTLPAKFLTEIYKELLHFLGPEDESDDIEQAEDKQSTSRSSQSRKSSAGGLRSIMDEVFRKISILENESEAIEPVERSISSEVSMRAQIKTEEDEIADIYQKSLPLELITDQSSERFSFQSAGESTEELSMHELEFPTSKAVKVASKTPSIEELPELVAQPEEAMKSEEEAHSEKHSGRGSDISKKSSLRSQRESANVPPHVRISEKSEIAEFQKSTSQISVEKPAGTRESAHVRISQEILQSEDKSEADEQRS"
        raw_entry2 = "comp10010_c0	   comp10010_c0_seq1:3-1250(-)	BDOR_007866-RB	 sp|Q23989|QUAI_DROME`Q23989`Q:16-895,H:11-888`54.89%ID`E:0`RecName: Full=Villin-like protein quail;`Eukaryota; Metazoa; Ecdysozoa; Arthropoda; Hexapoda; Insecta; Pterygota; Neoptera; Endopterygota; Diptera; Brachycera; Muscomorpha; Ephydroidea; Drosophilidae; Drosophila; Sophophora. .	  .	  .	  NOG304849	  GO:0003779^molecular_function^actin binding`GO:0051693^biological_process^actin filament capping`GO:0007015^biological_process^actin filament organization`GO:0035317^biological_process^imaginal disc-derived wing hair organization`GO:0007300^biological_process^ovarian nurse cell to oocyte transport	 MNQRLAMLQFNFIRQEVCSNSISDLKVDASFRKIAKNAICFHIWKIEEDRLEAEPKAQYGNFIDDCAYIIYAAAPKGIYVNQETITRETKPGTYLERFIHFWLGEKVSEQKRSNVAHKIQELDSYFNNVATEYRETQGNESARFLSYFKKGFTILSSSLLASKSSNRLYQLHGRKWLRCIEMDSISWDYFGSDYIMLLKTETNTFVWIGRSSSTAERRSALDWVTKLGMNASNVVIVDDGYEQSLPEKLKNQWNSFLPLSQRVVSQVSATPDRQQNNKIKIYKCGYRGTRLHLDQLDVVIPTKEDLSDTSTAYVLDGCLQGIWLWVGNMAPHQDKISAMGNGRAFVKKKKYPYSTPVIRVVQGHEPVEFIRLFPNWQQDATESIMAIKPVSTIFKRFDALTLSQRPKMAADTQLIDDGTGERKIYHVTKDQIMEKSQSKTVIFITNHCYVVEYTVMLPTASLADAQNVGVSTIIYQWNGSEANADDIANCERFALNTFEKLHKKAMFVQMCEYDETPHFLQIFDGKLIILQSERTLLSHHNNNINYISNEMSLMNRDYFVLRVYGDTSYNAKATEVYPLNTMSGKECYVVKTSHIWVWCGQSSTGDAREMAKNIGSLLGECSLVVEGKEPKEFWRSLTTYMSQPLINGSISSGSSNGSSTSPLNGSFVYNNNNNNVTKLRLQPQLFLAWLQRGKFFMREVIGYEQSDLSPESIYVLDTGLLSYIWLGRQASTYEKDKYMKIAQLYLESVPIARRPTTAVAVIRQDDEPNTFKGLFENWDHNLWNNYVSYELKRQAFMKQGNIPNTNDTITNGINGNGIIPSVLKNHLKDFDLHHKYPIVTLQQETDLLPPEVNPLKREVHLTHDDFVSLFNMSFWEFDELPVWKKQELKKKYKLF"
        self.anno.entries.append(raw_entry1.split('\t'))
        self.anno.entries.append(raw_entry2.split('\t'))
        self.assertEquals(2, len(self.anno.entries))

    def test_rename_mrna(self):
        self.assertEquals('BDOR_007864-RA', self.anno.entries[0][2])
        self.assertEquals('BDOR_007866-RB', self.anno.entries[1][2])
        self.anno.rename_mrna('BDOR_007866-RB', 'BDOR_foo')
        self.assertEquals('BDOR_foo', self.anno.entries[1][2])
        self.assertEquals('BDOR_007864-RA', self.anno.entries[0][2])

        


##########################
def suite():
    suite = unittest.TestSuite()
    suite.addTest(unittest.makeSuite(TestAnnotator))
    return suite

if __name__ == '__main__':
    unittest.main()
